### PR TITLE
Metrics partially defined for some sections

### PR DESCRIPTION
**Pull request by akvivas**

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Hi @akvivas - looks like your latex is not compiling! ("All checks have failed"). Check out the details above - can you please fix the bugs and let us know when this PR is mergeable? Thanks!

**Comment by akvivas** [comment]
it compiled ok in my fork!


--
Kathy Vivas
akvivas@gmail.com

**Comment by akvivas** [comment]
@drphilmarshall I am trying to make a new pull request with a refactoring of The Galaxy chapter. It seems I cannot create a new pull request until my previous one is closed. Can you do that please?

**Comment by willclarkson** [comment]
Hi Phil & Kathy - did this get resolved? The original pull request to which
Kathy refers here is for some material we contributed before the
refactoring, which is no longer relevant.

Is it possible to close Kathy's previous pull request so that she can make
another request to merge the new refactored .tex?

Thanks!

Will

--

Dr. Will Clarkson
Assistant Professor of Physics and Astronomy
University of Michigan-Dearborn
Students: please put your course code in the
title of emails to me
(ASTR330 or PHYS 150 lab or discussion).

**Comment by drphilmarshall** [comment]
Merging now - the build failure is due to the SN group. Thanks!

**Pull request merged**
