### PR TITLE
Patch 7

### PR DESCRIPTION
**Pull request by pmmcgehee**
This is an intermediate stage pull request for work I'm doing, mostly on the dust and star formation sections. I'm not done. I've cleaned up a few typos that where affecting the build.

### CODE REVIEW

**Comment by willclarkson** [comment]
Hi @pmmcgehee  - can you confirm please whether the latex of your interim updated version compiles successfully on your system? I am seeing a failure message for the checks on this pull request.

I'm nervous about merging the pull request without knowing if it will break the build. 

Thanks!! -- Will

**Comment by willclarkson** [comment]
@pmmcgehee , can you please fix the missing escape character in the reference to Hartmann & Kenyon 1996, in the discussion of FU Orionis in the material you are contributing? Here is the log from the build:

l.72 ...fter the prototypes FU Orionis (Hartmann &
                                                   Kenyon 1996)

It's probably easier for you just to zap this typo in the material you are contributing than for me to merge a pull request that breaks the build, then submit a fix, etc.

Thanks!!

Will  , cc @akvivas

**Comment by pmmcgehee** [comment]
I'll check it later today...

P

**Comment by pmmcgehee** [comment]
Pull Request #319 Patch 7#350 passed
<https://travis-ci.org/LSSTScienceCollaborations/ObservingStrategy/builds/125472643>

On Sun, Apr 24, 2016 at 12:22 PM, Peregrine McGehee <
peregrine.mcgehee@gmail.com> wrote:

> I'll check it later today...
>
> P
> On Apr 24, 2016 11:05 AM, "Will Clarkson" <notifications@github.com>
> wrote:
>
>> Hi @pmmcgehee <https://github.com/pmmcgehee> - can you confirm please
>> whether the latex of your interim updated version compiles successfully on
>> your system? I am seeing a failure message for the checks on this pull
>> request.
>>
>> I'm nervous about merging the pull request without knowing if it will
>> break the build.
>>
>> Thanks!! -- Will
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/pull/319#issuecomment-214010389>
>>
>


-- 
Dr. Peregrine M. McGehee
Santa Clarita, CA    (626) 993-4199

**Pull request merged**
