### PR TITLE
changed wfirst sections

### PR DESCRIPTION
**Pull request by jasondrhodes**
updated wfirst sections

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Hmm. I think something has gone wrong, Jason: the files that you committed seem to be a very old version, replacing no files at all! Take a look by clicking on the commit ID above (acc2f1c) 

The current versions of the WFIRST files can be viewed here:

https://github.com/LSSTScienceCollaborations/ObservingStrategy/tree/master/whitepaper/WFIRST

To get them, you need to `git pull` from the base repo at your local command line, with
```
git remote add base git@github.com:LSSTScienceCollaborations/ObservingStrategy.git
git pull base master
```
This brings down the latest version of the white paper, and merges it into your local copy. If you do that, and then 
```
git push origin master
```
we will then see your edits as well as David's and Matthew's. (I'll go ahead and merge David's so you can see them.) You may get conflicts in the tex files; if you do, you will need to resolve them - there's some help [here](https://github.com/drphilmarshall/GettingStarted/blob/master/README.md#top).

**Comment by jasondrhodes** [comment]
I managed to do the pull of the latest version and make my changes.  When I attempt to do the push, I get the error:

ERROR: Permission to LSSTScienceCollaborations/ObservingStrategy.git denied to jasondrhodes.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Probably I am making an error, but I don’t know what it is.  I have edited the latest files and can send them, unless someone is able to help me debug this issue.

Jason

**Comment by rhiannonlynne** [comment]
I believe that @drphilmarshall made 'master' of this repo a protected branch, so  I don't think you should be able to push directly from a fork. If you make another pull request here, you should be able  to merge from that (after the latex build passes).

**Comment by jasondrhodes** [comment]
Thanks for this help.  I have not used git before.  Are you suggesting I try to run the same commands again or different commands.  If you can tell me what command to run that will help.  Thanks.

Sent from my iPhone

On May 10, 2016, at 6:47 PM, Lynne Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe that @drphilmarshall<https://github.com/drphilmarshall> made 'master' of this repo a protected branch, so I don't think you should be able to push directly from a fork. If you make another pull request here, you should be able to merge from that (after the latex build passes).

**Comment by rhiannonlynne** [comment]
Well, to be honest, I'm a little confused. I believe Phil's commands (run
on a  local copy of your own fork of the ObservingStrategyWhitepaper repo),
should have tried to push back to master of your own fork. However, the
error message you got indicates that you were actually trying to push to
master of the LSSTScienceCollaborations version of the repo.

So - were you working on a local copy of your own fork? Maybe you can paste
in the contents of .git/config here?

**Comment by jasondrhodes** [comment]
[core]
     repositoryformatversion = 0
     filemode = false
     bare = false
     logallrefupdates = true
     symlinks = false
     ignorecase = true
     hideDotFiles = dotGitOnly
[remote "base"]
     url = git@github.com:LSSTScienceCollaborations/ObservingStrategy.git
     fetch = +refs/heads/*:refs/remotes/base/*


thanks for your help!

**Comment by rhiannonlynne** [comment]
Ah - ok. I think either Phil's instructions were missing quotes around "base" and "origin", or else you were in a somewhat weird state to start. Right now, your repo is only pointing at the LSSTScienceCollaborations version, not your own fork at all.

For my local copy of my own fork of the repo, the .git/config looks like: 

[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
        ignorecase = true
        precomposeunicode = true
[remote "origin"]
        url = git@github.com:rhiannonlynne/ObservingStrategy
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[remote "base"]
        url = git@github.com:LSSTScienceCollaborations/ObservingStrategy.git
        fetch = +refs/heads/*:refs/remotes/base/*


I think you can get out of this by doing:

git add remote "origin" <the location of your fork>

and then try "git push origin" again.

**Comment by drphilmarshall** [comment]
@jasondrhodes Can you please do
```
git remote -v
```
This will show you which remote repo, or repos, you are connected to. Mine looks something like this:
```
base    git@github.com:LSSTScienceCollaborations/ObservingStrategy.git (fetch)
base    git@github.com:LSSTScienceCollaborations/ObservingStrategy.git (push)
origin    git@github.com:drphilmarshall/ObservingStrategy.git (push)
origin    git@github.com:drphilmarshall/ObservingStrategy.git (fetch)
```
To get this, I did (a long time ago):
```
git clone git@github.com:drphilmarshall/ObservingStrategy.git
```
and then later,
```
git remote add base git@github.com:LSSTScienceCollaborations/ObservingStrategy.git
```
When you clone a repository, `git` remembers where it came from, and retains a connection to that original remote repo, naming it "origin". To connect to a different remote repo, you have to add it, and name it. In my case, the other repo is the base repo owned by LSSTScienceCollaborations, and so I named it "base". 

You don't have permissions to push directly to the base repo, but you can push to your fork. Before you do this, you need to merge in the latest version, though. Here is what I would do, given my set up as shown above:
```
git pull base master
```
This would fetch all the changes that have been made to the master branch of the base repo, and merge them into my current branch (which is probably called "master", but might not be - I would do `git status` to find out what branch I am on before pulling).

Once I was up to date locally, and I had fixed any conflicts that arose, I would do
```
git push origin master
```
which would attempt to take all the changes that I had made locally, and the ones that I just merged in, and merge them into the master branch on my fork (whose name is "origin", if you recall). 
 
Can you see how to do the same thing in your case? Did you clone from your fork, or the LSSTScienceCollaborations repo? Do you need to `git remote add` a new remote repo?

**Comment by drphilmarshall** [comment]
BTW all of this stuff and more is in the video tutorial I made, which is linked from [this FAQ](https://github.com/drphilmarshall/GettingStarted/blob/master/README.md#top)

**Comment by jasondrhodes** [comment]
Thanks I will give Lynn’s suggestions a try and watch the tutorial if that doesn’t help.

Jason

**Comment by jasondrhodes** [comment]
Thanks this helped and Phil’s video helped.  The main problem is I had somehow comingled the LSST version and the very old DESC version on my local fork (I think).  All sorts of problems.  I think I have successfully submitted a pull request with my changes.  If not, let me know.

Thanks

**Comment by drphilmarshall** [comment]
This PR was superceded by #408 - closing out.

**Pull request closed without merging**
