### PR TITLE
Update variables.tex

### PR DESCRIPTION
**Pull request by ShashiKanbur**

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Thanks @ShashiKanbur! Looks like your latex doesn't compile, would you mind fixing it please? No need to resubmit the pull request, it'll just track the commits your push.

l.31 ...a (also discussed in \ref{sec:\supernovae}
                                                  ), and explosion of high m...

Thanks again!

**Comment by ShashiKanbur** [comment]
Hello, I think the error here is in another section and perhaps not in the update to variables.tex that I added. Looking at the details below, its from a section on supernovae. Let me know.

! Undefined control sequence.

<argument> sec:\supernovae 

                           

l.31 ...a (also discussed in \ref{sec:\supernovae}

                                                  ), and explosion of high m...

?

**Comment by ShashiKanbur** [comment]
Hello, I think this error is from a document on supernovae and not the
update to variables.tex that I uploaded. Please let me know. Thanks,
Shashi

On Thu, Nov 26, 2015 at 12:54 PM, Phil Marshall <notifications@github.com>
wrote:

> Thanks @ShashiKanbur <https://github.com/ShashiKanbur>! Looks like your
> latex doesn't compile, would you mind fixing it please? No need to resubmit
> the pull request, it'll just track the commits your push.
>
> l.31 ...a (also discussed in \ref{sec:\supernovae}
> ), and explosion of high m...
>
> Thanks again!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/pull/226#issuecomment-159969335>
> .
>



-- 
Professor  and Chair,
Department of Physics,
SUNY Oswego,
Oswego, NY 13126
USA

"I know that I am mortal by nature, and ephemeral; but when I trace at my
pleasure the windings to and fro of the heavenly bodies I no longer touch
the earth with my feet: I stand in the presence of Zeus himself and take my
fill of ambrosia”  - Ptolemy

**Comment by drphilmarshall** [comment]
Thanks Shashi. Sorry for the delay!

**Pull request merged**
