### PR TITLE
added capability to compile a single section

### PR DESCRIPTION
**Pull request by fedhere**
##authored by federica bianco

i added the capability the PDF for one section only. this is implemented by creating a wrapper around each section called <section>_standalone.tex, where <section> is the name of the section main file, and by enabling in the Makefile the call to 'run' which takes as argument (ARG) the name of that section: e.g.

to compile only the "transients" section run 

$make run ARG=transients

note that the citations are compiled via the LSST_Observing_Strategy_White_Paper.aux, and .bbl, so if you want the citations to be compiled you must compile LSST_Observing_Strategy_White_Paper.pdf once (e.g. via $make all). If you do not you get a (non fatal) error .

note also that all the sections are compiled together with the introduction, cause it seemed like a good idea to me that the introduction was kept near and in mind, to remind the writers of the scope of the paper.

(the cadence section wrapper is called cadences_standalone.tex, so the command is $make run ARG=cadences, cause i was not sure why the name was 'cadexp2')

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Thanks @fedhere! This would be a useful piece of additional functionality, that I've heard others request too. I have a strong suggestion: instead of checking in a new standalone tex file for every section that needs to be compiled, can we not write a script (shell, or perl, or python) that *generates* the standalone tex file of *any section* inclusing those not written yet, and then compiles the latex into PDF? This would lead to a) much less clutter and b) sustainable approach to new content. What do you think? The standalone file you already made looks like an excellent template for this script to work from!

**Comment by fedhere** [comment]
great idea. i can (probably sometime in the weekend)

On Thu, Sep 24, 2015 at 12:14 PM, Phil Marshall <notifications@github.com>
wrote:

> Thanks @fedhere <https://github.com/fedhere>! This would be a useful
> piece of additional functionality, that I've heard others request too. I
> have a strong suggestion: instead of checking in a new standalone tex file
> for every section that needs to be compiled, can we not write a script
> (shell, or perl, or python) that *generates* the standalone tex file of *any
> section* inclusing those not written yet, and then compiles the latex
> into PDF? This would lead to a) much less clutter and b) sustainable
> approach to new content. What do you think? The standalone file you already
> made looks like an excellent template for this script to work from!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/pull/151#issuecomment-142976245>
> .
>



-- 

 /\|/\
   |*  Please consider the environment before printing this e-mail

**Comment by fedhere** [comment]
I added a python script to generate the standalone wrappers that create the files. python cause i think most people are going to be comfortable with it. Not the classiest script but it should be reader friendly enough 

 Usage: gen_standalone.py <section_name> (<section_name>, <section_name>...) <standalone_name>
this will generate a standalone tex file 
named <standalone_name>_standalone.tex which will include the 
paper Preface and all sections selected via command line

Compile the tex into a pdf file with 
$make run ARG=<standalone_name_root>

**Comment by drphilmarshall** [comment]
Cool! All: I did not test Fed's code, but trust her skillz. If you find bugs, please do issue her. But first, THANK YOU FED! This is going to make a good few people happy :-)

**Comment by fedhere** [comment]
ditto! there are bugs in my codes. there are bugs in all codes! they may
not affect there results, but bugs are always crawling around!


On Fri, Oct 23, 2015 at 6:13 PM, Phil Marshall <notifications@github.com>
wrote:

> Cool! All: I did not test Fed's code, but trust her skillz. If you find
> bugs, please do issue her. But first, THANK YOU FED! This is going to make
> a good few people happy :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/pull/151#issuecomment-150705003>
> .
>



-- 

 /\|/\
   |*  Please consider the environment before printing this e-mail

**Pull request merged**
