### PR TITLE
Update youngstars.tex

### PR DESCRIPTION
**Pull request by phartigan**
This file, together with the three pdf figures should be complete for this section now.

### CODE REVIEW

**Comment by phartigan** [comment]
[tts1.pdf](https://github.com/LSSTScienceCollaborations/ObservingStrategy/files/238210/tts1.pdf)
[tts2.pdf](https://github.com/LSSTScienceCollaborations/ObservingStrategy/files/238212/tts2.pdf)
[tts3.pdf](https://github.com/LSSTScienceCollaborations/ObservingStrategy/files/238211/tts3.pdf)

**Comment by willclarkson** [comment]
Hi @phartigan - I have re-opened your pull request in order to insert the figures and .tex you have contributed.

**Comment by willclarkson** [comment]
@drphilmarshall I'm going to go ahead and merge @phartigan 's pull request #347  since I don't think I have any other way to get to his new youngstars.tex file itself. This might break the build, but I will work on fixing the figure references immediately, so any disruption should be short-lived!

Will

**Comment by drphilmarshall** [comment]
Great, thanks both! Figures look a bit weird, like the bounding box is off. I bet this can be fixed with the right latex call. I'll issue it.

**Pull request merged**
