### PR TITLE
Update cepheids.tex

### PR DESCRIPTION
**Pull request by ShashiKanbur**
Hello, I made changes hoping to address Phil Marshall's comments. Section 5.2.1 "Description of Relevant Metrics" was written by someone else.

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Thanks, Shashi! The comments came from @StephenRidgway actually - hopefully he can take a look at [your changes](https://github.com/LSSTScienceCollaborations/ObservingStrategy/pull/442/files) and comment. Who wrote the metrics section? All of you should be listed at the start of the section, using the `\credit{}` macro. Great if you can add yourself and your colleagues. Thank you!

**Comment by StephenRidgway** [comment]
Hello @ShashiKanbur and @drphilmarshall - I have just reviewed the relevant section - 5.2 - and none of the recommended changes have been made, not even simple typos.  I wonder if the edited text was not merged back into the git system.

**Comment by drphilmarshall** [comment]
That sounds right, Steve. I'll merge this pull request now!

**Comment by drphilmarshall** [comment]
OK, git pull and see what you think now.

**Comment by StephenRidgway** [comment]
Got it.  I fixed a remaining typo, added a missing reference, and corrected the equation in cepheid section.  I’ll close out the task.

**Pull request merged**
