### PR TITLE
Fixed build error, made minor edits in Supernova section

### PR DESCRIPTION
**Pull request by sethdigel**
The LaTeX source was not building owing to some issue with $.  I fixed that and made some minor edits to the text.

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Thanks @sethdigel - I see there are conflicts on this branch now, would you mind resolving them please? Thanks!

**Comment by sethdigel** [comment]
Ok, done.  I guess the pull request now applies to the version that I just committed to my fork.

**Comment by sethdigel** [comment]
Well, now it really should work.  A figure had been added in the SN Cosmology section but the file name of the light curve that it pointed to was different from the name of the file in the figs directory.  I changed it to point at the file that is there.  I don't know whether this is helpful, but the LaTeX now builds.

**Comment by drphilmarshall** [comment]
Excellent! Thanks @sethdigel.

**Pull request merged**
