### PR TITLE
Update table 1

### PR DESCRIPTION
**Pull request by cbritt4**
Added line for X-ray novae (hundreds could be present in LSST data if current thinking on selection effects against short period systems is correct) and changed cataclysmic variables line to reflect dwarf novae in addition to flares.

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Thanks @cbritt4. What do you get when you do a `du -sh ObservingStrategy`? If it's 0.5Gb I'll need to cherry pick your commits, I think - and you'll need to delete your fork and make a fresh one (see #191)

**Comment by fedhere** [comment]
we are actually working on that table (and the following one) with a few faulkes here, so i suggest i keep @cbritt4 in the loop about it and incorporate his changes before we check in a new version

**Comment by fedhere** [comment]
@cbritt4  can you give me your email to add you to a google doc about that table?

**Comment by cbritt4** [comment]
Email is christopher.britt_at_ttu.edu

I got 71 Mb after issuing that command. I deleted my fork and got a new one before making the table changes, so I would have thought things would be fine unless something happened in the 30 seconds I was adding the changes in.

**Comment by drphilmarshall** [comment]
Great, thanks @cbritt4 !

**Pull request merged**
