### PR TITLE
Conclusions chapter (with Tensions and Tradeoffs)

### PR DESCRIPTION
**Pull request by drphilmarshall**
This is in response to #494 - @ivezic, I made a space for you to add your text in `tradeoffs.tex` in this branch (`issue/494/conclusions`). Let's add in any other commentary in the second "Conclusions from the Science Cases" section, and then see whether we can spread this over the rest of the chapter, merging with Steve's existing thoughts. I'm happy to do this once you've uploaded your work. If you can add in @connolly 's notes as well that would be most helpful. Thanks! I'll assign a reviewer (probably @bethwillman) when we've pulled everything together.

### CODE REVIEW

**Comment by drphilmarshall** [comment]
@ivezic @bethwillman I've merged Zeljko's conclusions into Chapter 12. I think Steve's discussion of the tensions and tradeoffs complements this very well, adding a layer of interpretation to Zeljko's concise list of actionable conclusions. I said I would assign a reviewer to this work before merging - I suggest that I ask Michael to take a look after merging, instead. Hope this sounds OK!

**Comment by michaelstrauss** [comment]
Indeed, the SAC is discussing the role we might plan in reviewing various aspects of the white paper.  I 
am happy to discuss the details at some time soon. 

						Thanks,  Michael

**Comment by drphilmarshall** [comment]
Great, thanks Michael! Would you like to take a look at the introduction
and conclusions chapters *before* we send the paper to the SAC on Friday?
The conclusions chapter is done, and the introduction chapter is nearly
done...

**Comment by michaelstrauss** [comment]
I am unlikely to have time to give you feedback on that timescale.  Having said that,
I am here at the JTM meeting (leaving mid-day Wednesday), so if you can send me 
something that I can look at quickly before I leave, I may be able to discuss briefly
with Zeljko and Beth. 

							-Michael

**Comment by drphilmarshall** [comment]
Of course, no problem. I'll email you a PDF chapter of conclusions, so that
you get an advance preview of Zeljko's "actionable inputs" to the project.
Beth's piece on the white paper (community)'s role in influencing LSST
observing strategy will probably have to wait until Friday, but if I get it
earlier I'll pass that along too.

**Pull request merged**
