### PR TITLE
added LSS conclusion about larger sky area

### PR DESCRIPTION
**Pull request by ivezic**
Added a sentence with the main LSS conclusion: 
"The large-scale structure studies are area-limited more than depth-limited and 
thus a larger sky coverage is preferred."

### CODE REVIEW

**Comment by tonytyson** [comment]
This is true only re probes of LSS that don't rely on cosmological 
volume such as weak lensing.

**Comment by ivezic** [comment]
Tony,
assuming that the WL science scales with the number of resolved galaxies, Neff=neff*Area,
we have very similar Neff (to within 5%) for Area = 18,000 sq.deg and Area~25,000 sq.deg. 
For more details, please look at page 43 in 
http://lsstsciencecollaborations.github.io/ObservingStrategy/IvezicBremerton2015.pdf
and see discussion of minion_1020 experiment in Chapter 2 from the white paper. 
We plan to produce a number of additional simulations for varying Area in this range and 
better quantify the Neff vs. Area curve (probably as soon as this calendar year).

**Comment by tonytyson** [comment]
The redshift range of the sample is a first order effect.  This is due to the lensing kernel.

**Comment by drphilmarshall** [comment]
Thanks both. For now, we'll take "large scale structure" to have its DESC meaning, as in galaxy clustering and BAO, not weak lensing (which is not fully tested). I'll merge this and add a comment to this effect  - thanks Zeljko!

**Comment by egawiser** [comment]
Looks like I can't review this anymore (on family vacation this week so apologies for being slow to respond).  But in any case, I strongly support Zeljko's phrasing of the conclusion, understood as Phil noted to apply to "LSS" and not weak lensing.  What's happening is that, even for relatively narrow redshift bins, our galaxy samples are so numerous that we're much deeper than the shot noise limit - hence we can give up depth and still trace the same cosmological volume.  In contrast, adding area directly increases cosmological volume.

**Comment by drphilmarshall** [comment]
Thanks, Eric! If you have suggested modifications, please do submit a PR
and I'll point the SAC at it when they turn their attention to the LSS
section. I think its fine to make changes to v0.99 during SAC review, as
long as they can see what is going on.

**Pull request merged**
