### PR TITLE
Fix compilation error

### PR DESCRIPTION
**Pull request by migueldvb**
Using new name for `NightSep_seasonLength.pdf` figure

### CODE REVIEW

**Comment by tanguita** [comment]
Oh I see my tex file didn't update! Will fix in a few minutes

**Comment by migueldvb** [comment]
@tanguita I think the PR should fix the problem.

**Comment by tanguita** [comment]
No I didn't commit the tex file. Will do in 5 minutes

**Comment by tanguita** [comment]
Done! Sorry for that.

**Comment by migueldvb** [comment]
Thanks, closing this pull request.

**Pull request closed without merging**
