### PR TITLE
WL section conclusions

### PR DESCRIPTION
**Pull request by tonytyson**
Hey @jmeyers314 I have just pasted the contents of the issue thread into a new Conclusions section of the WL.  What do you think?   It needs a brief intro to Zeljko's 10 Qs.

### CODE REVIEW

**Comment by MichelleLochner** [comment]
@tonytyson, @jmeyers314, would you guys like me to merge this now or wait until you've done further updates?

**Comment by tonytyson** [comment]
It needs a few words of summary which Josh or I can write by Sunday.
Thanks,
Tony

**Comment by tonytyson** [comment]
Michelle,
Yes go ahead and merge now.  We added a Conclusions section at the AHM, 
and I may add an intro to that soon.
Thanks,
Tony

**Comment by tonytyson** [comment]
Yes thanks!

**Pull request merged**
