### PR TITLE
update yso section

### PR DESCRIPTION
**Pull request by phartigan**
merged yso section.  The mini-survey can be cut out and repositioned elsewhere in the document
as required

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Thank very much, Pat! Will see what Peregrine makes of it next, but will
keep in mind th epotential special survey piece move.

**Comment by pmmcgehee** [comment]
Phil,

Could you please go ahead and commit these changes? I'll then make my own edits to close this up.

Thanks,
Peregrine

**Comment by drphilmarshall** [comment]
Here you go, Peregrine - thank for working on this!

I hope my slow merge didn't slow you up. For future reference, you can always add the remote repo and pull directly from it, and then submit a PR back (to Pat, in this case). For example
```
git remote add pat git@github.com/phartigan/ObservingStrategy.git
git checkout -b edit-pats-text
git pull pat master
...
git commit -am "Checked Pats text"
git push origin edit-pats-text
```
etc.

**Comment by pmmcgehee** [comment]
Thanks Phil for the merge .. and for the pointers!

Peregrine

On Wed, Jun 1, 2016 at 9:31 AM, Phil Marshall <notifications@github.com>
wrote:

> Here you go, Peregrine - thank for working on this!
>
> I hope my slow merge didn't slow you up. For future reference, you can
> always add the remote repo and pull directly from it, and then submit a PR
> back (to Pat, in this case). For example
>
> git remote add pat git@github.com/phartigan/ObservingStrategy.git
> git checkout -b edit-pats-text
> git pull pat master
> ...
> git commit -am "Checked Pats text"
> git push origin edit-pats-text
>
> etc.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/pull/452#issuecomment-223049489>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANP_2bPsgrcbeUaKoAuKX1EuIrokWIYkks5qHbPYgaJpZM4Im3vp>
> .
>



-- 
Dr. Peregrine M. McGehee
Santa Clarita, CA    (626) 993-4199

**Comment by pmmcgehee** [comment]
Hi Phil,

I submitted a pull request (Patch 10 #466) earlier this month, comprising
of a few edits to the young stars section and adding the cited papers to
the bibliography.

Best regards,
   Peregrine

On Wed, Jun 1, 2016 at 9:31 AM, Phil Marshall <notifications@github.com>
wrote:

> Here you go, Peregrine - thank for working on this!
>
> I hope my slow merge didn't slow you up. For future reference, you can
> always add the remote repo and pull directly from it, and then submit a PR
> back (to Pat, in this case). For example
>
> git remote add pat git@github.com/phartigan/ObservingStrategy.git
> git checkout -b edit-pats-text
> git pull pat master
> ...
> git commit -am "Checked Pats text"
> git push origin edit-pats-text
>
> etc.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/LSSTScienceCollaborations/ObservingStrategy/pull/452#issuecomment-223049489>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANP_2bPsgrcbeUaKoAuKX1EuIrokWIYkks5qHbPYgaJpZM4Im3vp>
> .
>



-- 
Dr. Peregrine M. McGehee
Santa Clarita, CA    (626) 993-4199

**Comment by drphilmarshall** [comment]
Thanks Peregine - your PR is now merged in.

**Pull request merged**
